config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [ :new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  scope :api, defaults: { format: :json }, module: :api, constraints: { subdomain: 'api' } do
    scope :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    if user.is? :admin
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end

      can :destroy, Comment do |comment|
        comment.user == user
      end

      can %i[read create like], :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id, counter_cache: :comments_counter
  after_save :update_comments_counter
  def update_comments_counter
    if post.comments_counter.nil?
      post.update(comments_counter: 1)
    else
      post.comments_counter += 1
      post.update(comments_counter: post.comments_counter)
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :update_likes_counter

  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id

  def update_likes_counter
    post.update(likes_counter: Like.where(post_id:).count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user, foreign_key: :author_id, counter_cache: :posts_counter
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  # Title must not be blank.
  validates :title, presence: true, length: { maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero.
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # LikesCounter must be an integer greater than or equal to zero.
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:posts_counter)
    if author.posts_counter.nil?
      author.update(posts_counter: 1)
    else
      author.posts_counter += 1
      author.update(posts_counter: author.posts_counter)
    end
  end

  def most_recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'

  ROLES = %i[admin default].freeze

  def is?(role_requested)
    role == role_requested.to_s
  end

  # PostsCounter must be an integer greater than or equal to zero.
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user_id: @user.id, post_id: @post.id, text: params[:comment][:text])
    @comment.save
    redirect_to user_post_path(@user, @post)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    flash[:notice] = 'The Comment was successfully deleted.'
    redirect_to user_post_url(User.find(params[:user_id]), Post.find(params[:post_id]))
  end

  def comment_params
    params.require(:comment).permit(:Text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(user: @user, post: @post)
    @like.save
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    # all posts for one user
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    # a single post - with post details for a specific user
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])

    @comments = @post.comments
    @likes = @post.likes
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(author: @user, title: params[:post][:title], text: params[:post][:text])

    if @post.save
      @post.update_post_counter
      flash[:notice] = 'Post created successfully'
      redirect_to user_post_path(@user, @post)
    else
      flash.alert = 'Something Went Wrong. Please Try Again!'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'The Post was successfully deleted.'
    redirect_to user_posts_url
  end

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/v1/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :find_post
  def index
    if @post
      @comments = Comment.where({ post_id: id }).order(:created_at)
      render json: { data: { comments: @comments } }, status: :ok
    else
      render json: { status: 'Failure', error: 'Post Not Found' }
    end
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user_id: @user.id, post_id: @post.id, text: params[:comment][:text])
    if @comment.save
      render json: @comment
    else
      render error: { error: 'Unable to create comments' }, status: 400
    end
    redirect_to user_post_path(@user, @post)
  end

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:Text)
  end
end

app/controllers/v1/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :find_user

  def index
    return unless @user

    @posts = @user.posts.order(:created_at)
    render json: { data: { posts: @posts } }, status: :ok
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<section>
  <h2>Add a comment: </h2>
  <%= form_with model: @comment, url: user_post_comments_path(@post) do |form| %>
    <div>
      <%= form.label :text, class: "form-label" %>
      <%= form.text_field :text, required: true, autofocus: true, placeholder: 'Write a comment', class: "form-input" %>
    </div>
    <%= form.submit "Comment", class: "form-btn" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= button_to "signin", new_user_session_path, method: :get  %>
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="posts-container">
  <div class="posts">
    <div class="img-user-container">
      <img class="img-user" src="<%= @user.photo %>" alt="User Avatar"/>
    </div>

    <div class="user-body">
      <a class="user-details-link">
        <h2 class="user-name"><%= @user.name%></h2>
        <p class="user-post-count">Number of posts: <%= @user.posts_counter || 0 %></p>
      </a>
    </div>
  </div>

  <div class="posts">
    <% @posts.includes(:user).each_with_index do |post, index| %>
      <%= link_to  user_post_path(@user, post.id) do %>
        <div class="post">
          <h3>Post #<%= index + 1 %></h3>
          <p><%= post.text%></p>
          <div class="post-details">
            <span class="comments">Comments: <%= post.comments_counter || 0 %>, </span>
            <span class="likes">Likes: <%= post.likes_counter || 0 %></span>
          </div>
        </div>
      <% end %>

      <ul class="comments-list">
        Comments:
        <div class="comment-group">
          <% post.most_recent_comments.each do |comment| %>
            <li class="comment"><%= comment.user.name %>: <%= comment.text %> </li>
          <% end %>
        </div>
      </ul>
    <% end %>
    <div class="will-paginate"></div>
  </div>

</section>

app/views/posts/new.html.erb
<section>
  <h2>New Post</h2>
  <% if @post.errors.any? %>
    <div>
      <% @post.errors.full_messages.each do |err| %>
      <p><%= err %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_with model: @post, url: user_posts_path(@user) do |form| %>
    <div>
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, required: true, autofocus: true, class: "form-input" %>
    </div>
    <div>
      <%= form.label :text, class: "form-label" %>
      <%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
    </div>
    <%= form.submit "submit", class: "form-button" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="posts-container">
  <div class="posts">
    <div class="post-detail-body">
      <h3>Post #<%= @post.id%> by <%= @post.author.name %></h3>
      <div class="post-comments">
        <span class="comments">Comments: <%= @post.comments_counter || 0%>, </span>
        <span class="likes">Likes: <%= @post.likes_counter || 0 %> </span>
      </div>
      <br>
      <div class="delete">
        <% if can? :destroy , @post %>
          <%= button_to 'Delete', user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-danger" %>
        <% end %>
      </div>
    </div>
    <p class="post-text alert"> <%= flash[:notice] %> </p>
    <p class="post-text"> <%= @post.text %> </p>
  </div>
  <div>
    <%= form_with model: @like, url:  user_post_likes_path(@user, @post) do |form|%>
      <%= form.submit 'Like post', class: 'submit' %>
    <%end%>
  </div>
  <ul class="comments-list">
    Comments:
    <% @comments.includes(:user).each do |comment| %>
      <li class="comment"><%= @user.name%>: <%= comment.text %></li>
      <% if can? :destroy, comment %>
        <%= button_to "Delete", user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-danger"%>
      <% end %>
    <% end %>
  </ul>
</section>


<button class="see-all-posts-link">
    <%= link_to "Create new comment", new_user_post_comment_path(@user, @post) %>
</button>

app/views/users/index.html.erb
<section class="users-container">
  <ul class="users-list">
    <% @users.each do |user| %>
      <li class="user">
        <div class="img-user-container">
          <img class="img-user" src="<%= user.photo %>" alt="User Avatar" />
        </div>

        <div class="user-details">
          <a class="user-details-link" href="/users/<%= user.id %>">
            <h2 class="user-name"><%= user.name%></h2>
            <p class="user-post-count">Number of posts: <%= user.posts_counter || 0 %> </p>
          </a>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<section class="user-info-container">
  <div class="user-info-cont-top">
    <div class=".img-user-container">
      <img class="img-user" src="<%= @user.photo %>" alt="User Avatar">
    </div>

    <div class="user-show">
      <div class="user-details-link">
        <h2 class="user-name"><%= @user.name %></h2>
        <p class="user-post-count">Number of posts: <%= @user.posts_counter || 0 %></p>
      </div>
    </div>
  </div>

  <div class="user-info-bio-div">
    <h3>Bio</h3>
    <p><%= @user.bio%></p>
  </div>
  
  <div class="user-posts-cont">
    <ul class="user-post-list">
      <% @user.recent_posts.each_with_index do |post, i| %>
        <li class="user-post">
          <a class="post-link" href=<%=user_post_path(@user, post)%>>
          <h3>Post #<%= i + 1 %> </h3>
          <%= link_to post.title, user_post_path(@user, post)%>
          <p><%= post.text %></p>
          <div class="post-interaction-cont">
            <span class="comments">Comments: <%= post.comments_counter || 0 %>, </span>
            <span class="likes">Likes:<%= post.likes_counter || 0 %></span>
          </div>
          </a>
        </li>
      <% end %>
    </ul>
  </div>

  <button class="see-all-posts-link">
    <%= link_to "See all posts", user_posts_path(@user) %>
  </button>
  
  <button class="see-all-post d-flex border">
    <%= link_to "Create post", new_user_post_path(@user) %>
  </button>

</section>